# Build DLL if changes apply on the CvGameCoreDLL folder
name: Build DLL

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Build DLL
        run: msbuild CvGameCoreDLL\CvGameCoreDLL.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: CvGameCoreDLL
          path: Assets/CvGameCoreDLL.dll
